<a href="https://colab.research.google.com/github/M0315G/PyTorch-Basics/blob/main/Section1%20-%20Getting%20Started%20with%20PyTorch/Gradient_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Gradients in PyTorch**

Basically, a numerical gradient tells you in which direction we need to move when you are machine learning i.e. positive or negative.

While the actual numerical value of the Gradient will tell you **how much** you should move. 

In the context of **Machine Learning**, what we normally do is take a loop over a group of tensors and compute gradients for them and then update the values of those tensors that are being 'learned' using the **product of gradients** and the **learning rate.**

Mathematically speaking, a gradient is a numerical representation of a **derivative** -- which means we have to ask the question - **"A gradient with respect to what?"**


And the answer is a **loss function**, in Machine Learning.

Lets try it out with a simple algebra example

``` X + 1 = 3 ```

In [1]:
import torch
torch.__version__

'1.8.1+cu101'

We'll initialize our tensor with a random initial guess.

In [3]:
# Creating an Random Tensor

X = torch.rand(1, requires_grad=True)  # Argument requires_grad is set to true so that we can update it based on the gradient.

And our formula is 

In [4]:
Y = X + 1.0
Y

tensor([1.9536], grad_fn=<AddBackward0>)

In [5]:
# Loss Function

def mse(Y):
  diff = 3.0 - Y
  return (diff * diff).sum()/2

The gradient on our X tells us which direction

In [6]:
loss =  mse(Y)
loss.backward()
X.grad

tensor([-1.0464])

Now, let's use the gradien to solve some algebra with simple Machine learning

In [8]:
learning_rate = 1e-3

# Training loop
for i in range(0, 10000):
  Y = X + 1.0

  loss = mse(Y)
  # Backpropogation of the gradient
  loss.backward()

  # here is the 'learning', so we turn off the gradients from being updated temporatily
  with torch.no_grad():
    # Gradient will tell you which direction you're off
    # so you'll go in the opposite direction to correct the weights
    X -= learning_rate * X.grad
    # and we zero out the gradients to get fresh values
    # on each learining loop iteration
    X.grad.zero_()



# Here is our answer
X

tensor([1.9999], requires_grad=True)