<a href="https://colab.research.google.com/github/M0315G/PyTorch-Basics/blob/main/Section1%20-%20Getting%20Started%20with%20PyTorch/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Tensors in PyTorch**

In [1]:
import torch
torch.__version__

'1.8.1+cu101'

Tensor in its simplest form is just a multidimentonal array.


There are a lot of ways to create a Tensor in PyTorch. Check out [this page](https://pytorch.org/docs/stable/torch.html#creation-ops).

In [2]:
# Creating an Empty Tensor

e = torch.empty(2,2)
e

tensor([[8.6591e-03, 3.0817e-41],
        [3.3631e-44, 0.0000e+00]])

Okay, you may think that it initializes them with *random values* but these above values are just something that was in memory. *They are not actually random.*

---

To create a tensor with **random values**, use the syntax given below

In [3]:
# Creating a Tensor with random values

r = torch.rand(2,2)
r

tensor([[0.1480, 0.7175],
        [0.6591, 0.0992]])

In [4]:
# Creating a Tensor initialized with zeros

z = torch.zeros(2,2)
z

tensor([[0., 0.],
        [0., 0.]])

In [6]:
# Creating a Tensor with specific constants

c = torch.full((2,2), 3)  # Replace 3 with any constant number you want your Tensor to take
c

tensor([[3, 3],
        [3, 3]])

The **best way** to create Tensors is **```torch.tensor()```** method. 

You can pass **various types of data** to it, for example - lists

In [7]:
l = torch.tensor([[1, 2], [3, 4]])
l

tensor([[1, 2],
        [3, 4]])

You can also interpolate it with **numpy arrays**, which is very handy to work with as most of the time your data will be in numpy format

In [8]:
import numpy as np

n = np.linspace(0, 5, 5)
n

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [9]:
# Turning it into a tensor

nn = torch.tensor(n)
nn

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000], dtype=torch.float64)

In [10]:
# You can even turn it back to numpy anytime you want to

nn.numpy()

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

You can also **specify the data type** of the tensor in any of the methods seen above.

In [11]:
s = torch.ones(3, 3, dtype=torch.float)
s

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

You can perform **all kinds of math operations** on them. Visit [this page](https://pytorch.org/docs/stable/torch.html#math-operations) for more info.

In [12]:
# addition

eye = torch.eye(3, 3)  # Creating a Identity tensor
eye + torch.zeros(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
# subtraction

eye - torch.ones(3, 3)

tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [15]:
# broadcast multiplication of a constant

eye * 3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [16]:
# or broadcast the division

eye / 3

tensor([[0.3333, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.3333]])

In [17]:
# or perform element-wise tensor multiplication

eye * torch.full((3,3), 4)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [18]:
# dot product

x = torch.rand(3, 4)
y = torch.rand(4, 3)
x@y

tensor([[1.0499, 0.7736, 0.6899],
        [1.3540, 0.9258, 1.0999],
        [1.7278, 1.1631, 1.4033]])