<a href="https://colab.research.google.com/github/M0315G/PyTorch-Basics/blob/main/Section2%20-%20Building%20a%20Neural%20Network/2.2-Creating_a_Neural_Network_using_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Neural network using PyTorch**

In [9]:
import torch

Initially, we'll only focus on creating the network and not on data or data loading, so we'll keep it simple and build up the  network step by step.

We'll use dummy random inputs and outputs and connect them in a network

**Inputs**

This is a tensor of *batch* of size 1, with 1 color channel (grey scale)

In [10]:
inputs = torch.rand(1, 1, 64, 64)
inputs

tensor([[[[0.3099, 0.9244, 0.3196,  ..., 0.5964, 0.8354, 0.6841],
          [0.3463, 0.0181, 0.8129,  ..., 0.1704, 0.3294, 0.5159],
          [0.4908, 0.0826, 0.1148,  ..., 0.2240, 0.0292, 0.5369],
          ...,
          [0.3475, 0.0795, 0.4649,  ..., 0.7598, 0.7866, 0.3365],
          [0.6011, 0.8944, 0.4615,  ..., 0.2252, 0.5668, 0.7598],
          [0.4788, 0.2840, 0.0184,  ..., 0.2873, 0.1201, 0.5369]]]])

**Outputs**

Pretend we're building a binary classifier, so we'll have two output possibilities, with a batch size of 1.

We'll use rand again, so each thing can be a little bit category 0 and a little bit category 1

In [11]:
outputs = torch.rand(1, 2)
outputs

tensor([[0.5189, 0.8194]])

In real time, these inputs and outputs will be your actual data, loaded up, in datasets, converted into batches.

Now, we'll create a  model with layers of linear -- these will themselves have tensors inside filled with random numbers called parameters, and these parameters is the thing that machine learning algorithms optimize to learn the mapping from an input to an output

In [12]:
model = torch.nn.Sequential(
    
    torch.nn.Linear(64, 256),
    torch.nn.Linear(256, 256),
    torch.nn.Linear(256, 2),
)

In [13]:
print(model)

Sequential(
  (0): Linear(in_features=64, out_features=256, bias=True)
  (1): Linear(in_features=256, out_features=256, bias=True)
  (2): Linear(in_features=256, out_features=2, bias=True)
)


Remember that this model isn't learning. We're just running our random initialized linear network over our Inputs

In [14]:
results = model(inputs)
results, results.shape

(tensor([[[[ 0.0715, -0.0050],
           [ 0.0384, -0.0638],
           [ 0.1322, -0.2000],
           [ 0.0833, -0.0859],
           [ 0.0313, -0.0425],
           [ 0.0917, -0.0610],
           [ 0.0073, -0.0462],
           [ 0.1380, -0.0408],
           [ 0.1273, -0.0075],
           [ 0.1384, -0.0238],
           [ 0.1089, -0.0311],
           [ 0.1207, -0.0037],
           [ 0.1537, -0.0231],
           [ 0.1773, -0.0965],
           [ 0.1408, -0.0981],
           [-0.0095,  0.0188],
           [ 0.1191, -0.0981],
           [ 0.1134, -0.0303],
           [ 0.1721, -0.0444],
           [ 0.0084, -0.0056],
           [ 0.0355, -0.0229],
           [ 0.0578, -0.0155],
           [ 0.0190, -0.0133],
           [ 0.0330, -0.0850],
           [ 0.1477, -0.0737],
           [ 0.0398, -0.0898],
           [-0.0530, -0.0802],
           [ 0.1976, -0.0572],
           [ 0.1022,  0.0092],
           [ 0.0675, -0.1517],
           [ 0.0340, -0.0468],
           [ 0.0838, -0.0519],
        